name: Build

on: [push, pull_request]

jobs:
  release:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: NPM Install
      run: |
        npm install
    - name: Build
      run: |
        npm run build
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: Info.txt
        files: |
          ./Output.zip

